<Gerenciador>:
    Menu:
        name: 'menu'

    Tarefas:
        name: 'tarefas'

<Menu>:
    BoxLayout:
        orientation: 'vertical'
        padding: 100, 10, 100, 50
        spacing: 20
        canvas:
            Color:
                rgb: (.5, .5, .5)
            Rectangle:
                pos: self.pos
                size: self.size
                source: 'imgs\\logoPython.jpg'
        Image:
            source: 'imgs/tarefas.png'
            size_hint_y:None
            height: 220
            allow_stretch:True #IMPORTANTE:permitir auterações no tamanho da imagem
        Button:
            id: um
            background_color: (.75, .75, .75, .8)
            font_size: 30
            text: 'Tarefas'
            on_release: app.root.current = 'tarefas'
            on_release: um.background_color = (.75, .75, .75, .8)
            on_press: um.background_color = 1, 0, 1, 1
        Button:
            id: dois
            background_color: (.75, .75, .75, .8)
            font_size: 30
            text: 'Assistente'
            on_press: dois.background_color = 1, 0, 1, 1
            on_release: dois.background_color = (.75, .75, .75, .8)
        Button:
            id: tres
            background_color: (.75, .75, .75, .8)
            font_size: 30
            text: 'Sair'
            on_press: tres.background_color = 1, 0, 1, 1
            on_release: app.stop()
            on_release: tres.background_color = (.75, .75, .75, .8)


<Botao@ButtonBehavior+Label>:
    canvas.before:
        Color:
            rgba: (.75, .75, .75, 1)
        Ellipse:
            pos: self.pos
            size: self.height, self.height
        Ellipse:
            pos: self.x + self.width - self.height, self.y
            size: self.height, self.height
        Rectangle:
            pos: self.x + self.height / 2.0, self.y




<Tarefas>:
    canvas:
        Color:
            rgb: (.5, .5, .5)
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        orientation: 'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    title: 'Tarefas'
                    on_release: app.root.current = 'menu'
                ActionSeparator:
                ActionButton:
                    text: 'Sair'
                    on_release: app.stop()
        ScrollView:
            bar_width: 10
            bar_inactive_color: 0, 1, 1, 0.5
            bar_color: 0, 1, 1, 1
            BoxLayout:
                id: box
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
        BoxLayout:
            size_hint_y:None
            height: 60
            TextInput:
                id: texto
            Button:
                text: '+'
                size_hint_x: None
                width: 70
                on_release: root.addWideget()

<Tarefa>:
    padding: 0, 0, 10, 0#vai em ordem circular começando da esquerda
    size_hint_y: None
    Label:
        color: 0, 1, 1, 1
        id: label
        font_size: 30
    Button:
        background_color: .9, 0, 0, 1
        text: 'X'
        size_hint_x: None
        width: 60
        on_release: app.root.get_screen('tarefas').ids.box.remove_widget(root)