a = input('digite algo: ')
print('o tipo primitivo desse valor é',type(a))
print('so tem espaços?',a.isspace())
print('é um numero?',a.isnumeric())
print('é alfabetico?',a.isalpha())
print('ele é alfanumerico?',a.isalnum())
print('esta em maisculas?',a.isupper())
print('esta em minuscolas?',a.islower())
print('ela esta capitalizada?',a.istitle())
