#############VARIÁVEIS CONTENDO CORES##################
AZUL = '#48D1CC'
CINZA = '#A9A9A9'
CINZA_CLARO = '#778899'
CINZA_MAIS_CLARO = '#DCDCDC'
ROXO = '#6A5ACD'
ROSA = '#FF69B4'
AZUL_CLARIN = '#00BFFF'
AZUL_CLARO_DA_PESTE = '#87CEFA'
VERMELHO = '#A52A2A'
VERDE_CLARO = '#00FF00'
SEI_LA = '#FFDEAD'
LARANJA = '#FF8C00'
AZUL_CINZA = '#B0C4DE'
PASTEL = '#E6E6FA'
AZURE = '#F0FFFF'
ROXO_COISADO = '#4B0082'
CINZA2 = '#778899'
ORANGE_RED = '#FF4500'
GOLD = '#FFD700'

#fontes
FONTE_VERDANA_BOLD = ('Verdana', 25, 'bold')
FONT_PAPYRUS_PEQUENA = ('papyrus', 17, 'bold')
FONT_PAPYRUS_GRANDE = ('papyrus', 30, 'bold')
FONT_PAPYRUS_EXTRA_GRANDE = ('papyrus', 60, 'bold')
FONTE_VERDANA_BOLD_PEQUENA = ('Verdana', 15, 'bold')
FONTE_BAUSHAUS_93_BOLD = ('Bauhaus 93', 25, 'bold')
FONTE_BAUSHAUS_93_BOLD_EXTRA_GRANDE = ('Bauhaus 93', 60, 'bold')

